services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_app_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/test_app
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  db_data:
